name: Lint and Test
categories: [testing]
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up node (also cache)
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npx lerna bootstrap
      - run: yarn lint
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up node (also cache)
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npx lerna bootstrap
      - run: yarn test
